app.documents.add(14291, 9449, 300, "GLLM");
app.activeDocument.layerSets.add();
app.activeDocument.activeLayer.name = "CMYK";
app.activeDocument.layerSets.add();
app.activeDocument.activeLayer.name = "SPOT";
app.activeDocument.layerSets.add();
app.activeDocument.activeLayer.name = "KHUNG";
 yPosition = 30;
 xPosition = 30;
 hLast = 0;
 wLast = 0;
 hAll=9449; wAll=14291;
